{--
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle
 
$T_n=n(n+1)/2$
 
$1, 3, 6, 10, 15, \dots$
Pentagonal
 
$P_n=n(3n - 1)/2$
 
$1, 5, 12, 22, 35, \dots$
Hexagonal
 
$H_n=n(2n - 1)$
 
$1, 6, 15, 28, 45, \dots$
It can be verified that $T_{285} = P_{165} = H_{143} = 40755$.
Find the next triangle number that is also pentagonal and hexagonal.
--}

ts :: [Int]
ts = 1 : zipWith (+) ts [2,3..]

ps :: [Int]
ps = 1 : zipWith (+) ps [4,7..]

hs :: [Int]
hs = 1 : zipWith (+) hs [5,9..]

union :: Ord a => [a] -> [a] -> [a]
union (x:xs) (y:ys) 
    | x == y = x : (union xs ys)
    | x < y = union (dropWhile (<y) xs) (y:ys)
    | otherwise = union (x:xs) (dropWhile (<x) ys)

main :: IO()
main = print $ head $ dropWhile (<=40755) $ union (union hs ps) ts